name: TaskManagerApp
options:
  createIntermediateGroups: true
  minimumXcodeGenVersion: 2.44.0
settings:
  base:
    SWIFT_VERSION: 6.0
    MACOSX_DEPLOYMENT_TARGET: 15.0
    PRODUCT_BUNDLE_IDENTIFIER: com.kachersoft.CyberTasks
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic
    GENERATE_INFOPLIST_FILE: YES
    INFOPLIST_KEY_CFBundleDisplayName: TaskManager
    INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.productivity
packages:
  TaskManagerUIComponents:
    path: ../TaskManagerUIComponents
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: 2.0.0
  generative-ai-swift:
    url: https://github.com/google/generative-ai-swift
    from: 0.5.0
targets:
  TaskManager:
    type: application
    platform: macOS
    sources:
      - path: Sources/TaskManager
    dependencies:
      - package: TaskManagerUIComponents
      - package: KeyboardShortcuts
      - package: generative-ai-swift
        product: GoogleGenerativeAI
schemes:
  TaskManager:
    build:
      targets:
        TaskManager: all
    run:
      config: Debug
    archive:
      config: Release
