name: TaskManagerApp
options:
  createIntermediateGroups: true
  minimumXcodeGenVersion: 2.44.0
settings:
  base:
    SWIFT_VERSION: 6.0
    MACOSX_DEPLOYMENT_TARGET: 15.0
    PRODUCT_BUNDLE_IDENTIFIER: com.kachersoft.CyberTasks
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_ENTITLEMENTS: Sources/TaskManager/TaskManager.entitlements
    GENERATE_INFOPLIST_FILE: NO
    INFOPLIST_FILE: Sources/TaskManager/Info.plist
  configs:
    Debug:
      CODE_SIGN_INJECT_BASE_ENTITLEMENTS: NO
    Release:
      ENABLE_HARDENED_RUNTIME: YES
      CODE_SIGN_INJECT_BASE_ENTITLEMENTS: NO
      OTHER_CODE_SIGN_FLAGS: --timestamp --options runtime
packages:
  TaskManagerUIComponents:
    path: ../TaskManagerUIComponents
  KeyboardShortcuts:
    url: https://github.com/sindresorhus/KeyboardShortcuts
    from: 2.0.0
  generative-ai-swift:
    url: https://github.com/google/generative-ai-swift
    from: 0.5.0
targets:
  TaskManager:
    type: application
    platform: macOS
    sources:
      - path: Sources/TaskManager
    dependencies:
      - package: TaskManagerUIComponents
      - package: KeyboardShortcuts
      - package: generative-ai-swift
        product: GoogleGenerativeAI
schemes:
  TaskManager:
    build:
      targets:
        TaskManager: all
    run:
      config: Debug

    archive:
      config: Release
